### ISSUE TITLE
Feature request: use adlfs to read azureml.opendatasets

### ISSUE THREAD

**Issue by raybellwaves** [dask/adlfs#102]
e.g. 

https://azure.microsoft.com/en-us/services/open-datasets/catalog/nyc-taxi-limousine-commission-green-taxi-trip-records/#AzureNotebooks

ddf = dd.read_parquet('abfs://NycTlcGreen.parquet", ...)

https://docs.microsoft.com/en-us/python/api/azureml-opendatasets/azureml.opendatasets?view=azure-ml-py

cc. @lostmygithubaccount

**Comment by raybellwaves** [comment]
This may be able to be closed per https://github.com/dask/adlfs/issues/117#issuecomment-700903363

I'll test later.

**Comment by raybellwaves** [comment]
@lostmygithubaccount, @meyetman, is there a way to know the name of the container for the open datasets?

e.g. I see [NOAA Integrated Surface Data (ISD)](https://azure.microsoft.com/en-us/services/open-datasets/catalog/noaa-integrated-surface-data/) is stored at 'isdweatherdatacontainer' per this [comment](https://github.com/dask/adlfs/issues/117#issuecomment-700903363).

How would I find the name for the container of [NYC Taxi & Limousine Commission - green taxi trip records](https://azure.microsoft.com/en-us/services/open-datasets/catalog/nyc-taxi-limousine-commission-green-taxi-trip-records/) for example?

**Comment by lostmygithubaccount** [comment]
you can find it on that page if you go to Data Access > Package: azure-storage. it is defined in the second cell `container_name = "nyctlc"`

**Comment by raybellwaves** [comment]
Thanks

![Screenshot from 2020-09-29 16-08-08](https://user-images.githubusercontent.com/17162724/94610262-047ea980-026e-11eb-998f-e8285ae35fa7.png)

**Comment by raybellwaves** [comment]
Works well for reading in a parquet file:

```
import dask.dataframe as dd

# from dask.distributed import Client
# client = Client()

storage_options = {'account_name': 'azureopendatastorage'}
ddf = dd.read_parquet('az://nyctlc/green/puYear=2019/puMonth=1/*.parquet', engine='pyarrow', storage_options=storage_options)
# len(ddf.vendorID) for testing
```

Have to do some fsspec magic to read in different datasets because of the folder structure:
```
from adlfs import AzureBlobFileSystem

fs = AzureBlobFileSystem(**storage_options)
files = fs.glob('nyctlc/green/puYear=2019/puMonth=*/*.parquet')
for i, f in enumerate(files):
    files[i] = 'az://' + f
ddf = dd.read_parquet(files,
                      engine='pyarrow',
                      storage_options=storage_options)
# len(ddf.vendorID) gives 3297967
```

cc. @martindurant is there a better way to append the protocol to the files?

I'll write this up in README and close out soon.

**Comment by martindurant** [comment]
Does `dd.read_parquet('nyctlc/green/puYear=2019/puMonth=*/*.parquet', ...)` not work?

**Comment by raybellwaves** [comment]
> Does dd.read_parquet('az://nyctlc/green/puYear=2019/puMonth=*/*.parquet', ...) not work?

It does. Not sure why I didn't try it. Thanks. Sorry for bothering.
