### ISSUE TITLE
AzureBlobFileSystem hanging on read/list operations

### ISSUE THREAD

**Issue by jhamman** [dask/adlfs#112]
**What happened**:

I'm trying to use AzureBlobFileSystem to generate a MutableMapping object that will work with zarr. I can create my file system object but all operations thereafter hang indefinitely. The traceback, shown below, indicates this could have something to do with the recent async work in fsspec. cc @martindurant on that point.

**What you expected to happen**:

I expected the filesystem to produce blobs. Here's an example where I simply try to retrieve the bytes of a know blob (not using the mapper interface).

**Minimal Complete Verifiable Example**:

```python
from adlfs import AzureBlobFileSystem

path = 'carbonplan-data/raw/terraclimate/4000m/raster.zarr/.zgroup'
fs = AzureBlobFileSystem(
    account_name="carbonplan",
    account_key=os.environ["BLOB_ACCOUNT_KEY"]
)

fs.cat(path)
```

Interrupting this code shows the following traceback:

```python-traceback
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-48-b68548dcfea1> in <module>
      7 )
      8 
----> 9 fs.cat(path)

/srv/conda/envs/notebook/lib/python3.7/site-packages/fsspec/asyn.py in cat(self, path, recursive, **kwargs)
    218 
    219     def cat(self, path, recursive=False, **kwargs):
--> 220         paths = self.expand_path(path, recursive=recursive)
    221         out = sync(self.loop, self._cat, paths, **kwargs)
    222         if (

/srv/conda/envs/notebook/lib/python3.7/site-packages/adlfs/spec.py in expand_path(self, path, recursive, maxdepth)
   1081 
   1082     def expand_path(self, path, recursive=False, maxdepth=None):
-> 1083         return sync(self.loop, self._expand_path, path, recursive, maxdepth)
   1084 
   1085     async def _expand_path(self, path, recursive=False, maxdepth=None):

/srv/conda/envs/notebook/lib/python3.7/site-packages/fsspec/asyn.py in sync(loop, func, callback_timeout, *args, **kwargs)
     62     else:
     63         while not e.is_set():
---> 64             e.wait(10)
     65     if error[0]:
     66         typ, exc, tb = error[0]

/srv/conda/envs/notebook/lib/python3.7/threading.py in wait(self, timeout)
    550             signaled = self._flag
    551             if not signaled:
--> 552                 signaled = self._cond.wait(timeout)
    553             return signaled
    554 

/srv/conda/envs/notebook/lib/python3.7/threading.py in wait(self, timeout)
    298             else:
    299                 if timeout > 0:
--> 300                     gotit = waiter.acquire(True, timeout)
    301                 else:
    302                     gotit = waiter.acquire(False)

KeyboardInterrupt: 
```

**Anything else we need to know?**:

Some related conversation here: https://github.com/zarr-developers/zarr-python/issues/618

**Environment**:

- Dask version: 2.25.0
- Python version: 3.7.8
- Operating System: Linux
- Install method (conda, pip, source): conda

**Comment by martindurant** [comment]
@hayesgb let me know if you need any help with this one (I don't have any azure...). 
I had no idea abfs had gone async!

@jhamman : fsspec has gone through a few iterations with respect to async to iron things out, it may be worth trying with various versions.

**Comment by hayesgb** [comment]
@jhamman if it helps, v0.4 implements comparability with azure storage 12.4.0 synchronously. Might be worth a try. 

@martindurant — it’s been a learning experience.  Added local caching and async filesystem operations in 0.5. I’d be grateful for any help.

**Comment by hayesgb** [comment]
Just checked and confirmed fs.cat("file.txt") returns expected result with
adlfs==0.4.0
fsspec==0.6.2
azure-storage-blob==12.4.0

**Comment by martindurant** [comment]
You mean fsspec 0.8.2? 

This line:
```
   1082     def expand_path(self, path, recursive=False, maxdepth=None):
-> 1083         return sync(self.loop, self._expand_path, path, recursive, maxdepth)
```
became `maybe_sync` in other backends, so as to use
 `_run_unti_done`, available I think since 0.8.1. This should avoid the deadlock.

Note @jhamman , that an immediate workaround for getting single files would be to use `cat_file`. I assume, though, that you would like to use concurrent downloads of zarr chunks.

**Comment by hayesgb** [comment]
@jhamman -- Fixed the cat failure with #113 -- "cat" needed to be implemented when inheriting from AsyncFileSystem.  Its currently in master.  I'd appreciate any feedback you can provide.

@martindurant -- You're right.  adlfs v0.4.0 is synchronous with fsspec==0.8.2.  Thanks for the note on run_until_done.  I'll take a look.

**Comment by jhamman** [comment]
Thanks for looking into this folks. I'm testing with master now and will report back once I have a result.

**Comment by hayesgb** [comment]
@martindurant -- Do you recommend using maybe_sync in place of sync in most instances?  Both seem to work equally well.

**Comment by martindurant** [comment]
Both will work when called from non-async code, but maybe_sync will do the right thing wherever its called from. You should make sure to have some async tests like https://github.com/intake/filesystem_spec/blob/master/fsspec/implementations/tests/test_http.py#L239

**Comment by jhamman** [comment]
When working off master, the above described issue is resolved. @hayesgb - feel free to close or leave open if you want to address @martindurant's `maybe_sync` comments first. Thanks for the quick fix!

**Comment by icfly2** [comment]
> @jhamman
> 
> Just checked and confirmed fs.cat("file.txt") returns expected result with
> adlfs==0.4.0
> fsspec==0.6.2
> azure-storage-blob==12.4.0

According to the new version of pip these three requirements are incompatible. But with:

```
adlfs==0.6.0
fsspec==0.8.5
azure-storage-blob==12.6.0
``` 

it works.
