### ISSUE TITLE
fs.glob() takes >3 minutes on a few thousand files 

### ISSUE THREAD

**Issue by lostmygithubaccount** [dask/adlfs#122]
**What happened**:
globing a few thousand files consistently takes 3-5+ minutes

**What you expected to happen**:
would expect it to take seconds, is this unreasonable? 

**Minimal Complete Verifiable Example**:

```python
%%time
from adlfs import AzureBlobFileSystem

container_name = "isdweatherdatacontainer"
storage_options = {"account_name": "azureopendatastorage"}
fs = AzureBlobFileSystem(**storage_options)
files = fs.glob(f"{container_name}/ISDWeather/year=*/month=*/*.parquet")
```

**Anything else we need to know?**:

**Environment**:

- Dask version: latest on pypi
- Python version: 3.8.5
- Operating System: macOS
- Install method (conda, pip, source): pip

**Comment by hayesgb** [comment]
It depends on the size of the files and your connection bandwidth.  Have you tried this operation using the Azurite storage?  That would eliminate bandwidth issue.

**Comment by hayesgb** [comment]
@lostmygithubaccount -- is this still a concern?

**Comment by lostmygithubaccount** [comment]
sorta but closing until I can investigate more - appreciate all the work on this package, it's great!
