### ISSUE TITLE
AzureBlobFileSystem.mkdir seems to have no effect with exist_ok=True

### ISSUE THREAD

**Issue by andersbogsnes** [dask/adlfs#130]
**What happened**:
When creating a new directory using the AzureBlobFileSystem, `mkdir` has no effect if the `exist_ok` flag is True, even though the container does not exist.

**What you expected to happen**:
The container to be created, and if the code is run again, no exception will be raised

**Minimal Complete Verifiable Example**:

```python
>>> from adlfs import AzureBlobFileSystem
>>> fs = AzureBlobFileSystem(account_name="myaccount", account_key="myaccountkey")
>>> fs.ls(".")
[]
>>> fs.mkdir("testcontainer", exist_ok=True)
>>> fs.ls(".")
[]
>>> fs.mkdir("testcontainer")
>>> fs.ls(".")
["testcontainer/"]
```

**Anything else we need to know?**:

**Environment**:
- adlfs version: 0.5.5
- Dask version: N/A
- Python version: 3.8
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): pip

**Comment by hayesgb** [comment]
Release 0.7.0 aligns adlfs mkdir() method to fsspec, per discussion [here](https://github.com/intake/filesystem_spec/issues/562)
