### ISSUE TITLE
ArrowIOError - server failed to authenticate on read_parquet

### ISSUE THREAD

**Issue by astrowonk** [dask/adlfs#145]
**What happened**:
dask `read_parquet` or AzureBlobFileSystem `.read_parquet` return an `Arrow error: IOError:`

**What you expected to happen**:
The command to return a pandas dataframe containing the information in the parquet blob.

**Minimal Complete Verifiable Example**:

```python
#ls works

$ myblobsystem = AzureBlobFileSystem(ACCOUNT_NAME,credential=ACCOUNT_KEY)
$ myblobsystem.ls('')

#copy file works without error
$ myblobsystem.get_file('example/test.pq','test.pq')

#read_parquet, same path, fails:
$ myblobsystem.read_parquet('example/test.pq') 

# or 
storage_options={'account_name': ACCOUNT_NAME,'credential':ACCOUNT_KEY}
ddf = dd.read_parquet('abfs://example/test.pq', storage_options=storage_options)



#output from either read_parquet
ArrowIOError: Arrow error: IOError: Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId...
Time:2020-11-30T17:44:30.8425576Z
ErrorCode:NoAuthenticationInformation
Error:None. Detail: Python exception: HttpResponseError

#EDITED to UPDATE: apparently I didn't upgrade to pyarrow 2.0 until just now. The error is similar but changes if I upgrade pyarrow.

HttpResponseError: Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId: 
Time:2020-11-30T18:51:27.6132379Z
ErrorCode:NoAuthenticationInformation
Error:None
```

**Anything else we need to know?**:

Credentials work both for listing blobs and in an Azure `BlobServiceClient`. Not sure why they work for listing containers/blobs but not for reading parquet?

**Environment**:

- pyarrow 2.0 (upgrade after failing with 0.15.1)
- Dask version: 2.26.0
- adlfs version: 0.5.7
- azure.blob version: 12.6.0
- Python version: 3.7.2
- Operating System: RHEL 7

- Install method (conda, pip, source): dask: conda, adlfs: pip

**Comment by lostmygithubaccount** [comment]
it looks like the `credential` input is not for account keys, there's a separate `account_key` input - can you try with that? 

e.g.

```python
myblobsystem = AzureBlobFileSystem(ACCOUNT_NAME,account_key=ACCOUNT_KEY)
```

not sure why ls would work though

**Comment by astrowonk** [comment]
Sorry, that's a bad constant name on my part - ACCOUNT_KEY is in fact as far as I know, a sas_token. I tried passing it in to AzureBlobFileSystem as a `sas_token` and it didn't like it (ls wouldn't work) but it worked as `credential`, and it works with azure's blob client, i.e.:
```python
from azure.storage.blob import BlobServiceClient

myclient = BlobServiceClient(f'https://{ACCOUNT_NAME}.blob.core.windows.net/',credential=ACCOUNT_KEY)
```

**Comment by astrowonk** [comment]
I have no idea why, but if I put my sas_token inside a azure `connection_string`, and pass that in via `storage_options` or while initing a `AzureBlobFileSystem` instance, then `read_parquet` works as expected! it's exactly the same string I was trying to pass in via credential, and there's nothing special about our blob_endpoint so this is a mystery.

**Comment by hayesgb** [comment]
The issue was that passing credential as a keyword to AzureBlobFileSystem created the filesystem object, and was listing the files, but the container_client attribute for the AzureBlobFile object was not being created.  This has been fixed in master.
