### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by TomAugspurger** [dask/adlfs#158]
I'd like to make a release with the recent performance improvements. Is that OK @hayesgb? I seem to have push access to PyPI, so I can take care of it.

Dask has recently switched to [Calver](https://github.com/dask/community/issues/100). I believe the various dask-foo projects will migrate to calver too. @martindurant do you have versioning plans for s3fs, gcsfs, and perhaps fsspec? Do you think they should use calver too?

**Comment by martindurant** [comment]
It really doesn't matter to me - I have no strong motivation to change, but no objection.

**Comment by TomAugspurger** [comment]
Cool. Let’s just stay with the old system for now then.

**Comment by hayesgb** [comment]
@TomAugspurger -- No issues.  Please go ahead.

Regarding the switch to Calver, I wasn't aware of the change, and don't have strong opinions.  Over a longer term, I would lean toward following the conventions used by dask and dask-foo.

**Comment by TomAugspurger** [comment]
0.5.9 is up on PyPI now.
