### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by TomAugspurger** [dask/adlfs#16]
@hayesgb it'd be nice to cut a release with the fixes for fsspec 0.6.0. Anything else that should go in first?

**Comment by hayesgb** [comment]
@TomAugspurger -- The PR from @AlbertDeFusco adds some nice functionality, in terms of supporting BlockBlobService and looks to fix the docker-compose issue.  I think we should merge those in and then release.  Thoughts?

**Comment by TomAugspurger** [comment]
Happy to do whatever. I likely won’t have time for this near term.

**Comment by AlbertDeFusco** [comment]
Perhaps just add the adlfs filesystems to the known_registry?

**Comment by hayesgb** [comment]
Just pushed out v0.1.2, which includes compatibility with fsspec>=0.6.0.  Cross-referencing the known_implementations question with this [discussion](https://github.com/intake/filesystem_spec/issues/206) the next release.
