### ISSUE TITLE
Incorrect homepage on `pypi`

### ISSUE THREAD

**Issue by dhirschfeld** [dask/adlfs#162]
The homepage on `pypi` points to [`hayesgb`](https://github.com/hayesgb/adlfs/)'s repo rather than here:
https://github.com/dask/adlfs/blob/de36e3dc69e4de9e7e45ddcd5cefb3997d02c389/setup.py#L13

This is confusing as the releases for the [`adlfs`](https://pypi.org/project/adlfs/#history) project come from *this* repo and there also happens to be a (defunkt?) [`dask-adlfs`](https://pypi.org/project/dask-adlfs/#history) page on `pypi`

**Comment by hayesgb** [comment]
Fixed with #163
