### ISSUE TITLE
Try DefaultAzureCredential by default?

### ISSUE THREAD

**Issue by dylanfprice** [dask/adlfs#201]
Use case: accessing blob storage from an Azure VM using a managed identity.

Using [fsspec](https://filesystem-spec.readthedocs.io/en/latest), I was able to get it to work via:
```python
from azure.identity.aio import DefaultAzureCredential         
import fsspec

fsspec.filesystem('az', account_name='myaccount', credential=DefaultAzureCredential())
```

However, using [petl](https://petl.readthedocs.io/en/stable/io.html#petl.io.remotes.RemoteSource), which uses fsspec under the hood, I am not sure how to inject the `DefaultAzureCredential`.

It might be nice to try the `DefaultAzureCredential` by default, since it is meant to cover a range of common use cases.

**Comment by dylanfprice** [comment]
Worked around this via the following. Not perfect but handles my use cases.
```python
import os

import adlfs
from azure.identity.aio import DefaultAzureCredential


class AzureBlobFileSystemWithDefaultCredentials(adlfs.AzureBlobFileSystem):
    def __init__(self, *args, **kwargs):
        has_credential = (
            "AZURE_STORAGE_ACCOUNT_KEY" in os.environ or "credential" in kwargs
        )
        if not has_credential:
            kwargs["credential"] = DefaultAzureCredential()
        super().__init__(*args, **kwargs)

# then before I try to open files
import fsspec
fsspec.register_implementation("az", AzureBlobFileSystemWithDefaultCredentials)
```

**Comment by isidentical** [comment]
In dvc, we also have a special condition to use `DefaultAzureCredential()`. It would be awesome to fallback on this by default on adlfs itself too! 
https://github.com/iterative/dvc/blob/547db15d343515d7056c7af4c311ae41b139916e/dvc/fs/azure.py#L72-L73

**Comment by thec0dewriter** [comment]
Hello @isidentical , @dylanfprice 
I tried to put together a PR, for falling back to use the DefaultAzureCredential. 
Let me know if this was kind of what were you expecting

**Comment by dylanfprice** [comment]
Yeah I am not familiar with the adlfs codebase but that looks about right to me!

**Comment by TomAugspurger** [comment]
This makes sense to me. I think the only potential issue to consider is that anonymous access to public storage accounts / blobs still works.

Anyone interested in submitting a pull request?

**Comment by dylanfprice** [comment]
There is one started in #222
