### ISSUE TITLE
mkdir does not create dirs with herarchical namespace enabled

### ISSUE THREAD

**Issue by lmmentel** [dask/adlfs#203]
I have a storage account (V2) with hierarchical namespace enabled and cannot get any of the `mkdir`, `mkdirs`, `makedir` or `makedirs` to actually create a directory:

Here is a minimal example:
```python
fs = fsspec.filesystem('abfs', connection_string=connection_string)
fs.makedir("test/test-dir/")
```
**What happened**:

In both cases, when `test` container exists and if it does not, behavior is the same and without `exist_ok=True` gives me
```python
...
StorageErrorException: Operation returned an invalid status 'Server encountered an internal error. Please try again after some time.'
...
During handling of the above exception, another exception occurred:

FileExistsError: Cannot overwrite existing Azure container -- test already exists.                         with Azure error Server encountered an internal error. Please try again after some time.
RequestId:efdce538-d01e-0002-0f21-24942d000000
Time:2021-03-28T22:23:39.9321554Z
ErrorCode:InternalError
Error:None
```

With `exist_ok=True` it just hangs for some time, does not give any output and does not create the directory.

**What you expected to happen**:

To the directory to be created for the specified path.

**Anything else we need to know?**:

I went through #137 and can create directories when hierarchical namespace option is disabled but then even when I include a trailing `/` a bunch of empty `<no_name>` files are produced in the dirs. I guess this is an artifact of creating virtual dirs.

**Environment**:

- Dask version: 2021.3.1
- Python version: 3.8.5
- Operating System: linux mint 20.1
- Install method (conda, pip, source): poetry

**Comment by hayesgb** [comment]
Based on [this discussion on fsspec](https://github.com/intake/filesystem_spec/issues/562), release 0.7 of adlfs will make mkdir a noop, to align be consistent with fsspec, and more closely align to the Azure blob API.

**Comment by lmmentel** [comment]
Thanks, a note somewhere in the docs would be nice, I guess since this is  one of the few issues mentioning mkdir.

Could you share your thoughts on the different behavior with hierarchical namespace enabled and not?

**Comment by hayesgb** [comment]
Based on my experience, I would not expect there to be a difference.  I our environment, we have hierarchical namespaces enabled and the functionality works.  The only time we've had a issue is if permissions do not allow the ServicePrincipal access to a given container / folder / directory.

**Comment by hayesgb** [comment]
Closing this as it seems to be stale.
