### ISSUE TITLE
Adjust for fsspec asyn changes and remove fsspec pin <=0.8.7

### ISSUE THREAD

**Issue by hayesgb** [dask/adlfs#205]
Based on [#581](https://github.com/intake/filesystem_spec/pull/581) on fsspec, there will be a significant change to the fsspec async API.  Until that work is finalized, adlfs will be pinned to fsspec <=0.8.7.

Pin to be removed when the work to fsspec is complete, and adlfs updated to align with changes.

**Comment by isidentical** [comment]
Is there any work already being done on this @hayesgb? Considering s3fs and gcsfs migrated, it is a bit problematic for applications that use all of the implementations at the same time. If there is no already started progress (or plans), I'd like to help on this.

**Comment by hayesgb** [comment]
No, that work has not started.  It would be great if you’d be willing to take that up.
