### ISSUE TITLE
Is there a way to connect to v2 storage URL like https://xxxx.dfs.core.windows.net

### ISSUE THREAD

**Issue by datawrangl3r** [dask/adlfs#207]
Is there a way to connect to Azure Storage v2 URL like https://xxxx.dfs.core.windows.net
I have a tenant ID, Client ID and Client Secret. However, when I specified these as storage options, and try to read a parquet, from a location like: `https://xxxx.dfs.core.windows.net/[container]/[file].parquet`, adlfs is throwing error as:

```
TypeError: _request() got an unexpected keyword argument 'tenant_id'
```

Here's my code:

```python
import dask.dataframe as dd

storage_options={'tenant_id': 'xxxxx', 'client_id': 'yyyyy', 'client_secret': 'zxzxzxz'}

ddf = dd.read_parquet('https://xxxx.dfs.core.windows.net/[container]/[file].parquet', storage_options=storage_options)
```

**Comment by wielrenner** [comment]
I tried it by setting the account url, but did not manage to make it work #169

**Comment by hayesgb** [comment]
Not using the https protocol.  It expects to receive the path as shown below:

```
import dask.dataframe as dd

storage_options={'account_name': ACCOUNT_NAME, 'account_key': ACCOUNT_KEY}

ddf = dd.read_csv('abfs://{CONTAINER}/{FOLDER}/*.csv', storage_options=storage_options)
ddf = dd.read_parquet('az://{CONTAINER}/folder.parquet', storage_options=storage_options)
```

The tenant_id, client_id, and client_secret would be passed in storage_options.
