### ISSUE TITLE
Adjust to fsspec's calendar versioning

### ISSUE THREAD

**Issue by isidentical** [dask/adlfs#223]
fsspec just released 2021.04.0 though adlfs still assumes it uses semantic versioning (e.g);
https://github.com/dask/adlfs/blob/e2a3807b8748a48eec366730a6d6ed60e4192cf4/setup.py#L36

Also one question that I have is whether adlfs will follow this convention of fsspec/s3fs/gcsfs and use calendar versioning or stay with the semantical versioning?

**Comment by hayesgb** [comment]
adlfs will have to switch to mirror the fsspec convention.

**Comment by hayesgb** [comment]
Linking to the [Dask discussion](https://github.com/dask/community/issues/100), with the intention of following the same convention

**Comment by hayesgb** [comment]
Will target first release of new convention to be July 1, as 2021.07.0
