### ISSUE TITLE
Azure ManagedIdentityCredential

### ISSUE THREAD

**Issue by rhjmoore** [dask/adlfs#226]
I have been developing a project for a client using Dask. One key element is accessing data from their Azure Data Lake Storage. Many routes are available to authenticate to ADLS, but unfortunately the route preferred at this client (and often by Enterprise clients) is the ManagedIdentityCredential. This authentication mechanism doesn't appear to work with Dask.

https://docs.microsoft.com/en-us/python/api/azure-identity/azure.identity.managedidentitycredential?view=azure-python

Is there anything stopping it from working / being implemented through storage_options, whereby we simply present a valid credential (or perhaps a function so that each machine in a cluster can request the ManagedIdentityCredential associated with that machine)?

**Comment by TomAugspurger** [comment]
Moved to adlfs. @rhjmoore please let us know if you think there's still an issue.

**Comment by rhjmoore** [comment]
Apologies for the delay - holidays and now access problems to the cluster. I will respond within a week.

**Comment by hayesgb** [comment]
@rhjmoore — This should work with the async credential, which can be found imported as
`import azure.identity.aio import ManagedIdentityCredential as AIOManagedIdentityCredential ` , following the same pattern used for fetching tokens for a ServicePrincipal

**Comment by rhjmoore** [comment]
Here are the results of my tests. I'm not sure I understand the specifics of the error being reported, but I also have some thoughts on why ManagedIdentityCredential might be inherently problematic with the current structure.

    from azure.identity.aio import ManagedIdentityCredential as ManagedIdentityCredential_aio
    aio_mi_cred = ManagedIdentityCredential_aio(client_id=client_id)
    aio_abfs = AzureBlobFileSystem(**{'account_name': <account_name>, 'credential': aio_mi_cred})
    aio_abfs.ls('data')

This code functions as expected and lists the contents of the container "data". But now we try to use dask to read that data. For context, we have already initiated a connection to a local cluster.

    ddf = dd.read_parquet('abfs://data/input_data.parquet', engine='pyarrow', columns=[<column subset>],
                                                 storage_options={'account_name':<account_name>, 'credential': aio_mi_cred})
    df = ddf.compute()  # This subset of columns fits in memory

This now fails as the work is kicked off with:
    distributed.protocol.pickle - INFO - Failed to serialise (<adlfs.spec.AzureBlobFileSystem at <mem-reference>>, <bound method ArrowDatasetEngine.read_partition of <class 'dask.dataframe.io.parquet.arrow.ArrowLegacyEngine'>>, Empty DataFrame
    ....
   Exception: cannot pickle 'weakref' object

I don't know for sure, but it seem as if this is something to do with the ability to pickle async credentials in general, but then others say that it has worked for them. Does that include reading a file with dask, or just adlfs itself?

Finally, my understanding of the ManagedIdentityCredential protocol, which is admittedly limited, is that it represents an authorisation on the machine itself which is attached and recognised uniquely by an ActiveDirectory server. Apologies if I'm misunderstanding how this works...

This would mean that in general the approach of supplying a ManagedIdentityCredential object created on the client to a dask scheduler for it to pass on to dask workers in a cluster on different machines could be inherently flawed. Will the ManagedIdentityCredential object pass security checks from the AD that it's being used from the machine authorised? Would we not need to pass the ManagedIdentityCredential class and client_id for the workers to create their own objects to use for their own authentications? Or would this requirement pass away if the client, scheduler and workers all are granted permission for that same client_id?

**Comment by rhjmoore** [comment]
> @rhjmoore — This should work with the async credential, which can be found imported as
> `import azure.identity.aio import ManagedIdentityCredential as AIOManagedIdentityCredential ` , following the same pattern used for fetching tokens for a ServicePrincipal

It should work, and it does for adlfs. Unfortunately it doesn't work for a dask cluster. I've attached some code showing the problem in this thread. Is there any further clarity that I could provide that would be useful?
