### ISSUE TITLE
[Question] Any particular reason for not returning exact matches on find(..., prefix=...)

### ISSUE THREAD

**Issue by isidentical** [dask/adlfs#239]
I was implementing the same API for the s3fs but the there is a slight edge case that I don't know whether done intentionally or not. When you are trying to `find('a/b/', prefix='file')` if there is a `a/b/file` in that same directory as well as `a/b/file_1` and `a/b/file_2` then it doesn't yield the exact match. 

https://github.com/dask/adlfs/blob/96958331854c5a67917d4c9a802a62720d091374/adlfs/spec.py#L934-L935

Is there any particular reason to excluding this match? If so, would it be possible to introduce some sort of keyword argument (like `include_full_match` or something like that) since otherwise we might need to do another API call to preserve the consistency of returns regardless of platform (s3fs/gcsfs/adlfs) which is not needed at all since the `_find()` method already finds that file if it exists.

**Comment by hayesgb** [comment]
No, there’s not a reason I’m aware of to exclude the exact match.  If it were intentional, then there should be a test to catch it.
