### ISSUE TITLE
3.6 regression: get_running_loop()

### ISSUE THREAD

**Issue by isidentical** [dask/adlfs#251]
The `asyncio.gat_running_loop()` is introduced in 3.7, but adlfs uses it which regressed the 3.6 support. The latest version of fsspec comes with `fsspec.asyn.get_running_loop()` which could be used instead of `asyncio.get_running_loop()` since it support 3.6 too!

**Comment by isidentical** [comment]
A gentle ping about this (it is blocking us from migrating to the newer versions of adlfs)

**Comment by hayesgb** [comment]
It's failing the DEV check...

**Comment by isidentical** [comment]
> It's failing the DEV check...

See https://github.com/intake/filesystem_spec/issues/688 for the reason.
