### ISSUE TITLE
anonymous data access behavior change

### ISSUE THREAD

**Issue by lostmygithubaccount** [dask/adlfs#254]
Noticed the comment below in the PR. It seems like #250 introduced breaking behavior where anonymous data access cannot be done by default.

This broke our example in Azure/azureml-examples, coinciding with the pypi release of adlfs: https://github.com/Azure/azureml-examples/actions?page=2&query=workflow%3Apython-sdk-tutorial-using-dask

Was this intended? Can the previous behavior be restored?

--

Isn't this PR backwards incompatible? In the past when you had only `account_name`, it was using anonymous auth and now it is using default credentials which is a completely different behavior unless you use the new `anon` option. I believe `anon` should be defaulted to `True`.

_Originally posted by @isidentical in https://github.com/dask/adlfs/issues/250#issuecomment-880601010_

**Comment by hayesgb** [comment]
Tagging @isidentical, [thec0dewriter](https://github.com/thec0dewriter), @TomAugspurger and @martindurant  for a broader discussion.

I'm open to either serving as the default behavior.  Originally, the intent was to align to the behavior of s3fs for consistency.  This explicitly implements the anon keyword, with a default value of `False` is consistent with both [s3fs](https://github.com/dask/s3fs/blob/562ed04dcc508263541a5f94fe090ef8efc1372e/s3fs/core.py#L95).

However, [gcsfs](https://github.com/dask/gcsfs/blob/07ef99ab22789bdeddea792e4322547691c0fcd4/gcsfs/core.py#L95) does not implement the `anon` kw, but instead tries a variety of approaches as well as accepting a value of anon for token.

 Assuming we want to move toward consistent behavior, what are the group's thoughts on a preferred behavior?  Should this move in the direction of s3fs or gcsfs?

**Comment by TomAugspurger** [comment]
I don't have a strong preference, though the previous behavior of providing only the account name implying anonymous access seems sensible.

**Comment by martindurant** [comment]
The difference between s3fs and gcsfs is one of historical convenience: whereas botocore takes case of finding various auth possibilities fo S3, leaving anon=True/False as the only realistic option, gcsfs has to manage the auth method itself, and "auto" may fail.

cc @thec0dewriter (I think the OP was supposed to tag instead of link)

**Comment by isidentical** [comment]
I'd also prefer an immediate release with `anon=False` and [yanking](https://pypi.org/help/#yanked) of the previous one considering a mismatch would result with a lot of confusion.

**Comment by hayesgb** [comment]
Also related to #256 -- Version 2021.7.0 has been yanked from pypi.

**Comment by isidentical** [comment]
Thanks for the yanking, though i can't see any new release on PyPI @hayesgb. Would you mind making one off (there were various other fixes between 0.7.7-2021.07.0 that we depended on, so we can't switch to an older version).

**Comment by hayesgb** [comment]
Just pushed the 2021.07.1

**Comment by lostmygithubaccount** [comment]
closing given this is fixed, thanks!
