### ISSUE TITLE
[BUG] Invalid blob type for PUT operation

### ISSUE THREAD

**Issue by element-wise** [dask/adlfs#260]
**What happened**:

Uploading large dataframe in chunks back to Azure Data Lake Gen 2 as a single file throws `ResourceExistsError` and then `HttpResponseError: The blob type is invalid for this operation.`

**What you expected to happen**:

Chunks are able to be uploaded as a single file.

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd

storage_options={'account_name': account_name, 'account_key': account_key}

# 170mb csv file
ddf = dd.read_csv(f'abfs://{src_path}', storage_options=storage_options, sample=25e6)

ddf.to_csv(f'abfs://{dest_path}', storage_options=storage_options, index=False, single_file=True)
```

**Anything else we need to know?**:

The first chunk gets uploaded successfully. It's when appending the next block to the existing file I see this error. 

**Environment**:

- Dask version: `2021.07.2`
- Python version: `3.8.8`
- Operating System: `Ubuntu`
- Install method (conda, pip, source): `pip`

**Comment by hayesgb** [comment]
Azure Blob doesn’t support appendBlobs by default.  You can create them using the AzureBlobFile object and setting “mode” = a (see line 1890).

**Comment by hayesgb** [comment]
Closing as inactive.
