### ISSUE TITLE
[BUG] isfile/isfolder for non-existent items takes ~50s

### ISSUE THREAD

**Issue by lmeyerov** [dask/adlfs#261]
**What happened**:

Calling `isile` + `isfolder` for path `abfs://c/f/2/3` when container & folder `c/f/2/` exists but file `3` does not takes `25s` + `25s`. 

**What you expected to happen**:

Expect to take < 1s, not 25s + 25s because calling the same `az storage blob exists ....` takes < 1s to get the error. This is extra surprising/negative due to asyncio support not landing yet or abfs, so it will block all other users of the python process

**Minimal Complete Verifiable Example**:

```python
   %%time
    storage_options = {
        'account_name': os.environ['AZ_STORAGE_ACCOUNT_NAME'],
        'account_key': os.environ['AZ_STORAGE_ACCOUNT_KEY']    
    }
    fs = fsspec.filesystem('abfs', **storage_options)
    print(fs.isfile(path), fs.isdir(path))
```
**Environment**:

RAPIDS 0.19 stable (conda):
fsspec `'2021.07.0'`
dask '2021.04.0'
ubuntu

**Comment by hayesgb** [comment]
Would you mind taking a look at the isfile branch with your use case and giving feedback?  This should be must faster with the changes on that branch.

**Comment by lmeyerov** [comment]
Hi @hayesgb , awesome -- will aim to try on w/th!

**Comment by hayesgb** [comment]
Merged this into master with #263

**Comment by lmeyerov** [comment]
@hayesgb 

Good news / bad news:

## Good news

```python
%%time
fs.isdir(path_missing)
fs.isfile(path_missing)
```
300ms: 20x+ faster!

## Bad news

```python
%%time
fs.isfile(path_existing)
```

=>

```
CPU times: user 10.5 ms, sys: 7.62 ms, total: 18.2 ms
Wall time: 47.5 ms
/conda/envs/rapids/lib/python3.7/site-packages/fsspec/asyn.py:25: RuntimeWarning: coroutine 'AzureBlobFileSystem._details' was never awaited
  result[0] = await coro
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
False
```

I expected `True` and no exception

## Setup

* fsspec '2021.07.0' (conda)
* adlfs '2021.08.1' (pip, no conda yet)
* docker / ubuntu 18.04 / python 3.7

```python
import adlfs, fsspec, os
storage_options = {
    'account_name': os.environ['AZ_STORAGE_ACCOUNT_NAME'],
    'account_key': os.environ['AZ_STORAGE_ACCOUNT_KEY']    
}
az_storage_container_name = os.environ['AZ_STORAGE_CONTAINER_NAME']
fs = fsspec.filesystem('abfs', **storage_options)

base_path = f'abfs://{az_storage_container_name}/data/datasets'
path = f'{base_path}/{dataset_id}'
fs.isdir(path)
```

**Comment by hayesgb** [comment]
@lmeyerov  -- I think the branch isfile3 should fix the await error, and I'll merge that into master immediately.  But for clarification:

At the top of the last entry, you cite `fs.isfile(path_existing)`, but in the bottom of your example you cite `fs.isdir(path)`.  Was this concern with isfile or isdir?

**Comment by lmeyerov** [comment]
@hayesgb  thanks! 

* The original issue (here) was 404s taking 30s instead of < 1s. When updating to fsspec to 2021.08.1, that seems to now be fast!

* The new issue (https://github.com/dask/adlfs/issues/265) is that files that *do* exist now incorrectly return `fs.isfile(legit_path) == False)` and an async warning. I'm trying to get `asynchronous=True ... await fs._isfile(path)` to work as a workaround, but haven't figured that out yet. Before 2021.08.1, that worked fine in sync mode.

**Comment by hayesgb** [comment]
Would you mind trying the master branch?  The await error is due to an error is fixed there.

**Comment by lmeyerov** [comment]
Checked -- the warning is gone, but wrong result + dir exists check is slowly downloading everything (afaict) instead of just checking: https://github.com/dask/adlfs/issues/265
