### ISSUE TITLE
ImportError: cannot import name 'infer_storage_options'

### ISSUE THREAD

**Issue by thenickg** [dask/adlfs#4]
Similar to: https://github.com/intake/intake/pull/388

```
from dask.bytes.utils import infer_storage_options
```
Should probably be:
```
try:
    from dask.bytes.utils import infer_storage_options
except ImportError:
    from dask.bytes.core import infer_storage_options
```
Possibly consider:
```
from fsspec.utils import infer_storage_options
```
as per: https://github.com/dask/dask/pull/5064
Not sure what else changed in dask that would break this plugin

**Comment by martindurant** [comment]
Please wait while this repo is rewritten. 
Indeed, fsspec is the way to do it, but the upstream code in azure-datalake-file-system is not compatible.
