### ISSUE TITLE
ADLFS documentation in Pandas and elsewhere 

### ISSUE THREAD

**Issue by lostmygithubaccount** [dask/adlfs#40]
Hello,

Not sure if a GitHub issue is appropriate for this but not sure how else to ask - what is preventing reading ADLFS in Pandas, cuDF, and other tools as you can with s3? See [pandas.read_csv](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) and [cudf.io.csv.read_csv](https://docs.rapids.ai/api/cudf/stable/).

Since this implements ADLFS in fsspec, is it simply a documentation issue? Is there more that is needed? 

Appreciate the work on this a lot!

**Comment by jamesmyatt** [comment]
I think the question belongs in the relevant consumer library. But for pandas, I think you just need to look at `get_filepath_or_buffer` in https://github.com/pandas-dev/pandas/blob/master/pandas/io/common.py.
