### ISSUE TITLE
Potential bug in fsspec.utils.infer_storage_options

### ISSUE THREAD

**Issue by andrii-ivaniuk** [dask/adlfs#45]
Hi,

I reported an issue for fsspec.
Here is a link: https://github.com/intake/filesystem_spec/issues/256
Could you please take a look?

**Comment by martindurant** [comment]
ping @hayesgb - should fsspec treat adl/bs URLs like it does s3/gcs? I suspect yes.

**Comment by hayesgb** [comment]
It should, but we will need to coordinate an update.  Currently, adlfs expects to receive both a "host" and a "path" key and they are concatenated within the library.  If you were to just add them to the list of protocols, that would break.    

Just let me know if you're going to make the update in fsspec.utils, and I can include an update in the next release.

**Comment by martindurant** [comment]
OK, so @andrii-ivaniuk , the current behaviour is apparently as expected. Did you experience some problem from this?

**Comment by andrii-ivaniuk** [comment]
@hayesgb Thanks for the response.
@martindurant No much problem.
