### ISSUE TITLE
EmptyDataError: No columns to parse from file

### ISSUE THREAD

**Issue by GautamKumarSkyPointCloud** [dask/adlfs#47]
Hi, I am unable to use the following code for my adls gen2 blob file.

import dask.dataframe as dd
from pkg_resources import parse_version
import fsspec
if parse_version(fsspec.__version__) < parse_version('0.6.2'):
    from fsspec.registry import known_implementations
    known_implementations['abfs'] = {'class': 'adlfs.AzureBlobFileSystem'}

STORAGE_OPTIONS={'account_name': 'account_key', 'account_key': 'account_key'}

ddf = dd.read_csv('abfs://{container_name}/test.csv', storage_options=STORAGE_OPTIONS)

Below is the error I am getting
EmptyDataError: No columns to parse from file

**Comment by GautamKumarSkyPointCloud** [comment]
Hi, I already have a adls gen 2 and i am able to connect to it using 
block_blob_service = BlockBlobService(account_name=account_name, account_key=account_key)
block_blob_service.get_blob_to_text(container_name, blob_location)

**Comment by raybellwaves** [comment]
see also https://github.com/dask/adlfs/issues/48#issuecomment-615545666

**Comment by raybellwaves** [comment]
@GautamKumarSkyPointCloud try now

**Comment by hayesgb** [comment]
Closing - no additional feedback from @GautamKumarSkyPointCloud.  Issues reported as resolved by @raybellwaves.
