### ISSUE TITLE
Unable to read a parquet file from blob with Hierarchical namespace enabled

### ISSUE THREAD

**Issue by raybellwaves** [dask/adlfs#54]
Following on from https://github.com/dask/adlfs/issues/48 I am unable to read a parquet file from blob.

I am able to read a csv from the blob but reading a parquet files gives a persistent `azure.common.AzureHttpError`: 

```
>>> dd.read_parquet('abfs://tmp/tmp.parquet',
                     storage_options=storage_options)
RROR:azure.storage.common.storageclient:Client-Request-ID=591c7559-85aa-11ea-91b3-095b84d992ed Retry policy did not allow for a retry: Server-Timestamp=Thu, 23 Apr 2020 21:36:24 GMT, Server-Request-ID=c751a7f7-a01e-0002-5bb7-194764000000, HTTP status code=500, Exception=Server encountered an internal error. Please try again after some time. ErrorCode: InternalError<?xml version="1.0" encoding="utf-8"?><Error><Code>InternalError</Code><Message>Server encountered an internal error. Please try again after some time.RequestId:c751a7f7-a01e-0002-5bb7-194764000000Time:2020-04-23T21:36:25.4617555Z</Message></Error>.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ray/local/bin/anaconda3/envs/adlfs/lib/python3.8/site-packages/dask/dataframe/io/parquet/core.py", line 225, in read_parquet
    meta, statistics, parts = engine.read_metadata(
  File "/home/ray/local/bin/anaconda3/envs/adlfs/lib/python3.8/site-packages/dask/dataframe/io/parquet/fastparquet.py", line 202, in read_metadata
    parts, pf, gather_statistics, fast_metadata = _determine_pf_parts(
  File "/home/ray/local/bin/anaconda3/envs/adlfs/lib/python3.8/site-packages/dask/dataframe/io/parquet/fastparquet.py", line 150, in _determine_pf_parts
    pf = ParquetFile(
  File "/home/ray/local/bin/anaconda3/envs/adlfs/lib/python3.8/site-packages/fastparquet/api.py", line 111, in __init__
    with open_with(fn2, 'rb') as f:
  File "/home/ray/local/bin/anaconda3/envs/adlfs/lib/python3.8/site-packages/fsspec/spec.py", line 718, in open
    f = self._open(
  File "/home/ray/local/bin/anaconda3/envs/adlfs/lib/python3.8/site-packages/adlfs/core.py", line 592, in _open
    return AzureBlobFile(
  File "/home/ray/local/bin/anaconda3/envs/adlfs/lib/python3.8/site-packages/adlfs/core.py", line 621, in __init__
    super().__init__(
  File "/home/ray/local/bin/anaconda3/envs/adlfs/lib/python3.8/site-packages/fsspec/spec.py", line 956, in __init__
    self.details = fs.info(path)
  File "/home/ray/local/bin/anaconda3/envs/adlfs/lib/python3.8/site-packages/fsspec/spec.py", line 501, in info
    out = self.ls(path, detail=True, **kwargs)
  File "/home/ray/local/bin/anaconda3/envs/adlfs/lib/python3.8/site-packages/adlfs/core.py", line 488, in ls
    elif self._matches(
  File "/home/ray/local/bin/anaconda3/envs/adlfs/lib/python3.8/site-packages/adlfs/core.py", line 422, in _matches
    gen = self.blob_fs.list_blob_names(
  File "/home/ray/local/bin/anaconda3/envs/adlfs/lib/python3.8/site-packages/azure/storage/blob/baseblobservice.py", line 1362, in list_blob_names
    resp = self._list_blobs(*args, **kwargs)
  File "/home/ray/local/bin/anaconda3/envs/adlfs/lib/python3.8/site-packages/azure/storage/blob/baseblobservice.py", line 1437, in _list_blobs
    return self._perform_request(request, _converter, operation_context=_context)
  File "/home/ray/local/bin/anaconda3/envs/adlfs/lib/python3.8/site-packages/azure/storage/common/storageclient.py", line 446, in _perform_request
    raise ex
  File "/home/ray/local/bin/anaconda3/envs/adlfs/lib/python3.8/site-packages/azure/storage/common/storageclient.py", line 374, in _perform_request
    raise ex
  File "/home/ray/local/bin/anaconda3/envs/adlfs/lib/python3.8/site-packages/azure/storage/common/storageclient.py", line 359, in _perform_request
    _http_error_handler(
  File "/home/ray/local/bin/anaconda3/envs/adlfs/lib/python3.8/site-packages/azure/storage/common/_error.py", line 115, in _http_error_handler
    raise ex
azure.common.AzureHttpError: Server encountered an internal error. Please try again after some time. ErrorCode: InternalError
<?xml version="1.0" encoding="utf-8"?><Error><Code>InternalError</Code><Message>Server encountered an internal error. Please try again after some time.
RequestId:c751a7f7-a01e-0002-5bb7-194764000000
Time:2020-04-23T21:36:25.4617555Z</Message></Error>
```

This can be tested using
```
> conda create -n adlfs python=3.8
> conda activate adlfs
> conda install -c conda-forge dask fastparquet
> pip install adlfs
> python

>>> import pandas as pd
>>> import dask.dataframe as dd
>>> from distributed import Client
>>> client = Client()

>>> storage_options = {'account_name': 'ACCOUNT_NAME',
                        'account_key': 'ACCOUNT_KEY'}

>>> d = {'col1': [1, 2, 3, 4], 'col2': [5, 6, 7, 8]}
>>> df = pd.DataFrame(data=d)

>>> df = dd.from_pandas(df, npartitions=2)

>>> dd.to_parquet(df=df,
                  path='abfs://tmp/tmp.parquet',
                  storage_options=storage_options)

>>> dd.read_parquet('abfs://tmp/tmp.parquet',
                     storage_options=storage_options)
```

You can see the versions on the packages here:

<details><summary><tt>> conda list</tt>:</summary>

_libgcc_mutex             0.1                        main  
adal                      1.2.2                    pypi_0    pypi
adlfs                     0.2.4                    pypi_0    pypi
azure-common              1.1.25                   pypi_0    pypi
azure-datalake-store      0.0.48                   pypi_0    pypi
azure-storage-blob        2.1.0                    pypi_0    pypi
azure-storage-common      2.1.0                    pypi_0    pypi
bokeh                     2.0.1            py38h32f6830_0    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
certifi                   2020.4.5.1       py38h32f6830_0    conda-forge
cffi                      1.14.0                   pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
click                     7.1.1              pyh8c360ce_0    conda-forge
cloudpickle               1.3.0                      py_0    conda-forge
cryptography              2.9.2                    pypi_0    pypi
cytoolz                   0.10.1           py38h516909a_0    conda-forge
dask                      2.14.0                     py_0    conda-forge
dask-core                 2.14.0                     py_0    conda-forge
distributed               2.14.0           py38h32f6830_0    conda-forge
fastparquet               0.3.3            py38hc1659b7_0    conda-forge
freetype                  2.10.1               he06d7ca_0    conda-forge
fsspec                    0.6.2                    pypi_0    pypi
heapdict                  1.0.1                      py_0    conda-forge
idna                      2.9                      pypi_0    pypi
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7  
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libllvm8                  8.0.1                hc9558a2_0    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                hc7e4089_6    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
llvmlite                  0.31.0           py38h4f45e52_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.2                he1b5a44_0    conda-forge
markupsafe                1.1.1            py38h1e0a361_1    conda-forge
msgpack-python            1.0.0            py38hbf85e49_1    conda-forge
ncurses                   6.2                  he6710b0_0  
numba                     0.48.0           py38hb3f55d8_0    conda-forge
numpy                     1.18.1           py38h8854b6b_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    1.0.3            py38hcb8c335_1    conda-forge
partd                     1.1.0                      py_0    conda-forge
pillow                    7.0.0            py38hb39fc2d_0  
pip                       20.0.2                   py38_1  
psutil                    5.7.0            py38h1e0a361_1    conda-forge
pycparser                 2.20                     pypi_0    pypi
pyjwt                     1.7.1                    pypi_0    pypi
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
python                    3.8.2                hcf32534_0  
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.3.1            py38h1e0a361_0    conda-forge
readline                  8.0                  h7b6447c_0  
requests                  2.23.0                   pypi_0    pypi
setuptools                46.1.3                   py38_0  
six                       1.14.0                     py_1    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.31.1               h62c20be_1  
tblib                     1.6.0                      py_0    conda-forge
thrift                    0.11.0          py38he1b5a44_1001    conda-forge
tk                        8.6.8                hbc83047_0  
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.4            py38h1e0a361_1    conda-forge
typing_extensions         3.7.4.1          py38h32f6830_3    conda-forge
urllib3                   1.25.9                   pypi_0    pypi
wheel                     0.34.2                   py38_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.4                h516909a_0    conda-forge
zict                      2.0.0                      py_0    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.4                h6597ccf_3    conda-forge

</details>

**Comment by raybellwaves** [comment]
I just created my own blob via the [Azure free account](https://azure.microsoft.com/en-us/free/) and it worked fine:

```
>>> dd.read_parquet('abfs://tmp/tmp.parquet', storage_options=storage_options)
Dask DataFrame Structure:
                col1   col2
npartitions=2              
0              int64  int64
2                ...    ...
3                ...    ...
Dask Name: read-parquet, 2 tasks
```

May have to see how the other blob is setup.

**Comment by raybellwaves** [comment]
Blob that worked:

Location: East US, West US (Primary: Available, Secondary: Available)
Replication: Read-access geo-redundant storage (RA-GRS)

Blob that did not work:

Location: East US 2
Replication: Locally-redundant storage (LRS)

**Comment by raybellwaves** [comment]
Closing as not related to `adlfs`. I am able to 'fix' the storage account i'll post it at https://stackoverflow.com/questions/61220615/dask-read-parquet-from-azure-blob-azurehttperror

**Comment by raybellwaves** [comment]
I believe I got to the bottom of it.

When creating a blob to match the one that wasn't working I switched on 'Hierarchical namespace' Data Lake Storage Gen2 and reproduced the error.

**Comment by raybellwaves** [comment]
![image](https://user-images.githubusercontent.com/17162724/80170602-54b65900-85b6-11ea-9291-b7c8fc2ba634.png)

**Comment by raybellwaves** [comment]
Not sure if related to https://github.com/dask/adlfs/blob/master/requirements.txt#L1

**Comment by hayesgb** [comment]
Thanks for digging into this @raybellwaves.  I just looked at the configuration on one of the accounts I'm using with adlfs daily.  There, Heirarchical namespace is turned on, but Replication is set to Geo-redundant Storage.  Can you confirm if that combination works in your test space?

**Comment by raybellwaves** [comment]
I believe the below matches your configuration and I was not able to read the parquet file.

![Screenshot from 2020-04-24 07-56-01](https://user-images.githubusercontent.com/17162724/80210670-22cae400-8602-11ea-80c2-1c795c5960bf.png)
![Screenshot from 2020-04-24 07-59-13](https://user-images.githubusercontent.com/17162724/80210682-28c0c500-8602-11ea-9519-85e7678985f3.png)

**Comment by raybellwaves** [comment]
Can kind of see it in the blob logs but not in much detail

![Screenshot from 2020-04-24 08-21-10](https://user-images.githubusercontent.com/17162724/80211954-a2f24900-8604-11ea-9b49-56d60e13b5bf.png)

**Comment by raybellwaves** [comment]
Wanted to be a bit more thorough on the blob configuration. I am unable to read when I turn on the hierarchical namespace.

![Screenshot from 2020-05-04 22-11-54](https://user-images.githubusercontent.com/17162724/81029814-5ef91280-8e54-11ea-9231-6841a8f46a24.png)

**Comment by hayesgb** [comment]
Thanks for sharing this @raybellwaves.  Just to add to it, my current instance is:

- Region: East US 2
- Replication: GRS
- Performance: Standard
- Secure Transfer: Enabled
- Access Tier: Hot
- Hierarchical Namespace: Enabled
- NFSv3: Disabled

Any chance you can check the other parameters?  Unfortunately, it will be at least another week before I can circle back to work on this.

**Comment by raybellwaves** [comment]
No problem. Thanks for sharing your config. Will do.

**Comment by raybellwaves** [comment]
![Screenshot from 2020-05-05 07-29-52](https://user-images.githubusercontent.com/17162724/81061372-3ac42280-8ea2-11ea-9719-315e99235584.png)

**Comment by raybellwaves** [comment]
This has been working fine during the last couple of days. Closing.
