### ISSUE TITLE
Directories identified as files in walk()

### ISSUE THREAD

**Issue by dfigus** [dask/adlfs#55]
I'm running adlfs==0.2.4 & fsspec==0.6.2 and observed the following behavior:

Given the folllowing folder structure in ADLS Gen1:

```
/folder/subfolder1/subfolder1_1
/folder/subfolder1/subfolder1_2
...
```
If I do a

`_, directories, files = next(fs.walk('/folder'))`

I get `subfolder1` in `files `and not `directories`. I did a short debugging and it looks like that the official Microsoft `AzureDLFileSystem.ls()` returns `"type" = "DIRECTORY"`, but in fsspec's `AbstractFileSystem.walk()` `"type" = "directory"` is expected. Therefore all folders are treated as files.

**Comment by hayesgb** [comment]
Fixed on PR.
