### ISSUE TITLE
Create conda-forge adlfs-feedstock

### ISSUE THREAD

**Issue by raybellwaves** [dask/adlfs#60]
Following on from https://github.com/dask/adlfs/issues/22 I would be interested in creating and maintaining adlfs-feedstock (along with @hayesgb and @martindurant) to build the package on conda-forge.

I've done this for one package (https://github.com/conda-forge/xskillscore-feedstock) and my normal procedure is to release on pypi then use the tar.gz in the meta.yaml.

Following some discussion here https://github.com/dask/adlfs/issues/22#issuecomment-586803021 I haven't had the the need to automate this build. I simply change a couple of lines after the package is released on pypi.

**Comment by jamesmyatt** [comment]
I was just about to ask what the plans for a conda-forge release are.

**Comment by martindurant** [comment]
Yes, @raybellwaves , please go ahead and tag us on the PR. For a pure-python package like this, it should be straight-forward.

**Comment by raybellwaves** [comment]
Very much WIP https://github.com/conda-forge/staged-recipes/pull/11831

**Comment by raybellwaves** [comment]
Closed via https://github.com/conda-forge/staged-recipes/pull/11831
