### ISSUE TITLE
Clarify role of requirements.txt

### ISSUE THREAD

**Issue by jamesmyatt** [dask/adlfs#61]
As I understand it, your `requirements.txt` file contains the requirements for the local development environment. Is this correct? In which case, I think it would be better renamed to `dev-requirements.txt`, moved to "dev" extras, or something else.

**Comment by hayesgb** [comment]
Appreciate the feedback.  Updated requirements.txt to reflect packages in setup.py for those that want to install just requirements, and added dev-requirements.txt with versioneer. etc.

**Comment by jamesmyatt** [comment]
Thanks
