### ISSUE TITLE
Unexpected behaviour when directories aren't explicitly created

### ISSUE THREAD

**Issue by jamesmyatt** [dask/adlfs#63]
See this unit test in #62, which fails: https://github.com/dask/adlfs/pull/62/commits/6eb9574cd6ae1771213f415ea0cf238b089c7896

The [first failure](https://dev.azure.com/dask-dev/dask/_build/results?buildId=1241&view=logs&j=d090b295-8b65-5b33-df45-4b0e4ec519f8&t=8e34badb-79ac-5acb-45f0-df0af76ba649&l=132) is at the line:

```
assert fs.ls("test_deep") == ["test_deep/a/"]
```

which fails because `ls` throws a FileNotFoundError. Since the container was created, it certainly shouldn't give FileNotFound.

*update*: #64 might be more fundamental and the fix for that might fix this.

**Comment by hayesgb** [comment]
I incorporated your additional tests into master.  It is still failing, but current master branch returns:
`assert fs.ls("test_deep") == ["test_deep/a/"]
E       AssertionError: assert ['test_deep/a/b/'] == ['test_deep/a/']
E         At index 0 diff: 'test_deep/a/b/' != 'test_deep/a/'
E         Full diff:
E         - ['test_deep/a/']
E         + ['test_deep/a/b/']
E         ?               ++
`

**Comment by hayesgb** [comment]
Now passing deep_paths tests

**Comment by jamesmyatt** [comment]
Thanks 👍
