### ISSUE TITLE
Importing azure.common, which is no longer part of 'install_requires'

### ISSUE THREAD

**Issue by andersbogsnes** [dask/adlfs#74]
**What happened**:
If `AzureBlobFilesystem._get_token_from_service_principal` is called, it will raise an import error as azure.common is no longer part of the requirements

https://github.com/dask/adlfs/blob/1778049d1b341d8526a412efcaa70ff7b81b0521/adlfs/core.py#L362

I can't find any reference to token_credentials being used anywhere, so this might just be a dead code path, in which case I can remove it in a PR. 

Since I'm not sure what token_credential is actually used for, I don't know what to substitute it with - otherwise I would just make a PR fixing it

**Comment by hayesgb** [comment]
This import will be removed in the latest release, which fixes the ability to authenticate with a ServicePrincipal.
