### ISSUE TITLE
Connect to ADLS Gen2 using Service Principal

### ISSUE THREAD

**Issue by pedrosanchezr** [dask/adlfs#75]
Hi,

I'm starting using Dask and I wanted to connecto to ADLS Gen2.
I was not finding any way to do it using a service principal and checking the code I see something that I'm not sure if make sense.

In the condition of line 324 of core.py, we are calling "self._get_token_from_service_principal()" if we don't have certain values, but one of those values is the "client_id", which seems to be required later inside that method to generate the credentials. So I guess that if I include the client_id, this is not going to call "self._get_token_from_service_principal()" and if I do not include it, I won't have the right one when it tries to create the "ServicePrincipalCredentials".

Is this ok? How can I use it correctly?

https://github.com/dask/adlfs/blob/c91106fbe9184e7c75efbc40cf292a7d5b8c8491/adlfs/core.py#L324

**Comment by hayesgb** [comment]
Fixed in adlfs 0.3.2, with supporting documentation.
