### ISSUE TITLE
use of 'az' as a shorter version of 'abfs'

### ISSUE THREAD

**Issue by raybellwaves** [dask/adlfs#78]
[_Moved from filesystem_spec to here_](https://github.com/intake/filesystem_spec/issues/373)

This is more of a discussion than a feature request.

Looking at `known_implementations` in fsspec there are `gcs` and `gs` which both point to `gcsfs.GCSFileSystem`. Could `az` be created as a shorter version of `abfs`?

az is common with Azure CLI syntax e.g. docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#run-azcopy.
As someone who is very lazy I prefer two key strokes instead of four.

**Caveats**

Unlike gs and s3, Azure has two classes (adlfs.AzureDatalakeFileSystem and adlfs.AzureBlobFileSystem). I imagine you can't use az for both classes.

**Proposed solution**

Use az as a shortcut for 'abfs': {'class': 'adlfs.AzureBlobFileSystem'}. Given this is for the latest version of storage (Azure Datalake Gen2 and Azure Blob Storage). In addition my 50 % reduction in key strokes motivation doesn't apply to `adl` (Azure Datalake Gen1).

**Comment by hayesgb** [comment]
I'm open to the idea, but I'd like to get feedback from @martindurant.  When we settled on abfs as the protocol, it was based on the fact that abfs:// is the defined protocol for AzureBlobFileSystem, as described [here](https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-abfs-driver).

**Comment by hayesgb** [comment]
I just saw that this discussion started in fsspec.  I'm OK with it.  As a side-note, I've also started to see the "az://" show up in at least one other place as well.

**Comment by martindurant** [comment]
You can, of course, have both protocols.

**Comment by raybellwaves** [comment]
Yeah I was thinking of making it akin to `gcs` and `gs`. I imagine replacing `abfs` with `az` would probably lead too many breaking changes for users.

I'm thinking of seeing the following in [`fsspec.registry.known_implementations`](https://github.com/intake/filesystem_spec/blob/master/fsspec/registry.py#L88):
```
'abfs': {'class': 'adlfs.AzureBlobFileSystem', 'err': 'Install adlfs to access Azure Datalake Gen2 and Azure Blob Storage'},
'az': {'class': 'adlfs.AzureBlobFileSystem', 'err': 'Install adlfs to access Azure Datalake Gen2 and Azure Blob Storage'}
```

**Comment by martindurant** [comment]
OK, so go ahead! 
I think the protocol attribute of the implementation class in this repo should also change to a tuple of the possible strings, `("az", "abfs")` at the same time

**Comment by hayesgb** [comment]
@raybellwaves -- I'm good with this.  Are you planning to submit a PR?

**Comment by raybellwaves** [comment]
Closed via https://github.com/dask/adlfs/pull/111
